module.exports =
    [
        {
            key: '',
            label: 'Vehicles',
            src: 'categories/1.png',
            route: '',
            sub: [
                { label: 'Cars and Trucks', route: '' },
                { label: 'Motorcycle', route: '' },
                { label: 'Other Vehicles and Trailers', route: '' },
                { label: 'Boats Powersports', route: '' },
                { label: 'Ports and Accessories', route: '' },
            ]
        },
        {
            key: '',
            label: 'Real Estate',
            src: 'categories/2.png',
            sub: [
                { label: 'Commercial', route: '' },
                { label: 'Condominium', route: '' },
                { label: 'Land', route: '' },
                { label: 'Manufactured Homes', route: '' },
                { label: 'Residential', route: '' },
                { label: 'Other Real Estate', route: '' },
            ]
        },
        {
            key: '',
            label: 'Mobile Gadgets',
            src: 'categories/10.png',
            sub: [
                { label: 'Smart Watches', route: '' },
                { label: 'Smart Phone', route: '' },
                { label: 'Smart Watch Accessories', route: '' },
                { label: 'Cellphone Accessories', route: '' },
                { label: 'Phone Cards and Sim Cards', route: '' },
                { label: 'Cell Phone and Smartphone Parts', route: '' },
                { label: 'Other Cell Phones and Accessories', route: '' },
            ]
        },
        {
            key: '',
            label: 'Computers and Laptops',
            src: 'categories/12.png',
            sub: [
                { label: 'Ipads, Tablets, and eBook Readers', route: '' },
                { label: 'Ipad/Tablet/eBook Accessories', route: '' },
                { label: 'Tablet and eBook Readers Parts', route: '' },
                { label: 'Laptop and Netbooks', route: '' },
                { label: 'Desktops and All-In-Ones', route: '' },
                { label: 'Laptop and Desktop Accessories', route: '' },
                { label: 'Cables and Connectors', route: '' },
                { label: 'Computer Components and Parts', route: '' },
                { label: 'Drives, Storage and Blank Media ', route: '' },
                { label: 'Enterprise Networking, Servers', route: '' },
                { label: 'Home Networking and Connectivity', route: '' },
                { label: 'Keyboards, Mice and Pointing ', route: '' },
                { label: 'Monitors, Projectors and Accessories', route: '' },
                { label: 'Power Protection, Distribution', route: '' },
                { label: 'Printers, Scanners and Supplies ', route: '' },
                { label: 'Other Computers and Networking', route: '' },
            ]
        },
        {
            key: '',
            label: 'Cameras and Photography equipments',
            src: 'categories/11.png',
            sub: [
                { label: 'Camera Drones', route: '' },
                { label: 'Digital Cameras', route: '' },
                { label: 'Camera and Photo Accessories', route: '' },
                { label: 'Digital Photo Frames', route: '' },
                { label: 'Film Photography', route: '' },
                { label: 'Flashes and Flash Accessories', route: '' },
                { label: 'Lenses and Filters', route: '' },
                { label: 'Lighting and Studio', route: '' },
                { label: 'Manuals and Guides', route: '' },
                { label: 'Replacement Parts and Tools', route: '' },
                { label: 'Tripods and Supports', route: '' },
                { label: 'Video Production and Editing', route: '' },
                { label: 'Vintage Movie and Photography', route: '' },
                { label: 'Other Cameras and Photo', route: '' },
            ]
        },
        {
            key: '',
            label: 'Electronics',
            src: 'categories/3.png',
            sub: [
                { label: 'Portable Audio and Headphones', route: '' },
                { label: 'TV, Video and Home Audio', route: '' },
                { label: 'Vehicle Electronics and GPS', route: '' },
                { label: 'Home Automation', route: '' },
                { label: 'Home Surveillance', route: '' },
                { label: 'Home Telephones and Accessories', route: '' },
                { label: 'Multipurpose Batteries and Power', route: '' },
                { label: 'Radio Communication', route: '' },
                { label: 'Gadgets and Other Electronics', route: '' },
            ]

        },
        {
            key: '',
            label: 'Fashion and Clothing',
            src: 'categories/4.png',
            sub: [
                { label: 'Baby and Toddler Clothing', route: '' },
                { label: 'Kids Clothing, Shoes and Accessories', route: '' },
                { label: 'Costumes Reenactment, Theater ', route: '' },
                { label: 'Cultural and Ethnic Clothing', route: '' },
                { label: 'Dancewear', route: '' },
                { label: "Men's Accenssories", route: '' },
                { label: "Men's Clothing", route: '' },
                { label: "Men's Shoes", route: '' },
                { label: 'Uniforms and Work Clothing', route: '' },
                { label: "Unisex Clothing, Shoes and Accessories", route: '' },
                { label: "Wedding and Formal Occasion", route: '' },
                { label: "Women's Shoes", route: '' },
                { label: 'Vintage', route: '' },
                { label: 'Wholesale, Large and Small Lots', route: '' },
            ]
        },
        {
            key: '',
            label: 'Jewelry and Watches',
            src: 'categories/13.png',
            sub: [
                { label: "Children's Jewelry", route: '' },
                { label: 'Engagement and Wedding', route: '' },
                { label: 'Ethnic, Regional and Tribal ', route: '' },
                { label: 'Fashion Jewelry', route: '' },
                { label: 'Fine Jewelry', route: '' },
                { label: "Handcrafted, Artisan Jewelry", route: '' },
                { label: "Jewelry Boxes and Organizers", route: '' },
                { label: "Jewelry Design and Repair", route: '' },
                { label: 'Loose Beads', route: '' },
                { label: "Loose Diamonds and Gemstones", route: '' },
                { label: "Men's Jewelry", route: '' },
                { label: "Vintage and Antique Jewelry", route: '' },
                { label: 'Watches', route: '' },
                { label: 'Other Jewelry and Watches', route: '' },
                { label: 'Wholesale Lots', route: '' },
            ]
        },
        {
            key: '',
            label: 'Travel and Luggages',
            src: 'categories/14.png',
            sub: [
                { label: "Airline", route: '' },
                { label: 'Campground and RV Parks', route: '' },
                { label: 'Car Rental ', route: '' },
                { label: 'Cruises', route: '' },
                { label: 'Lodging', route: '' },
                { label: "Luggage", route: '' },
                { label: "Luggage Accessories", route: '' },
                { label: "Maps" },
                { label: 'Rail', route: '' },
                { label: "Travel Accessories", route: '' },
                { label: "Vacation Packages", route: '' },
                { label: "Other", route: '' }
            ]
        },
        {
            key: '',
            label: 'Home and Garden',
            src: 'categories/15.png',
            sub: [
                { label: "Bath", route: '' },
                { label: 'Bedding', route: '' },
                { label: 'Fresh Cut Flowers and Supplies ', route: '' },
                { label: 'Furniture', route: '' },
                { label: 'Greeting Cards and Party Supply', route: '' },
                { label: "Holiday and Seasonal Decor", route: '' },
                { label: "Home Decor", route: '' },
                { label: "Home Improvement", route: "" },
                { label: 'Household Supplies and Cleaning', route: '' },
                { label: "Kids and Teens at Home", route: '' },
                { label: "Kitchen, Dining and Bar", route: '' },
                { label: "Lamps, Lighting and Ceiling Fands", route: '' },
                { label: "Major Appliances", route: "" },
                { label: 'Rugs and Carpets', route: '' },
                { label: "Tools", route: '' },
                { label: "Window Treatments and Hardware", route: '' },
                { label: "Yard, Garden and Outdoor Living  ", route: '' },
                { label: "Other Home and Garden", route: '' },
            ]
        },
        {
            key: '',
            label: 'Tickets and Experiences',
            src: 'categories/16.png',
            sub: [
                { label: "Sports Tickets", route: '' },
                { label: 'Concert Tickets', route: '' },
                { label: 'Theater Tickets ', route: '' },
                { label: 'Theme Park and Club Passes', route: '' },
                { label: 'Parking Passes', route: '' },
                { label: "Special Experiences", route: '' },
                { label: "Other Tickets and Experiences", route: '' }
            ]
        },
        {
            key: '',
            label: 'Health and Beauty',
            src: 'categories/17.png',
            sub: [
                { label: "Bath and Body", route: '' },
                { label: 'Dietry Supplements, Nutrition', route: '' },
                { label: 'Fragrances ', route: '' },
                { label: 'Hair Care and Styling', route: '' },
                { label: 'Health Care', route: '' },
                { label: "Makeup", route: '' },
                { label: "Massage", route: '' },
                { label: "Medical, Mobility and Disability", route: '' },
                { label: 'Nail Care, Manicure and Pedicure', route: '' },
                { label: 'Natural and Homeopathic Remedies ', route: '' },
                { label: 'Oral Care', route: '' },
                { label: 'Over-the-Counter Medicine', route: '' },
                { label: "Salon and Spa Equipment", route: '' },
                { label: "Shaving and Hair Removal", route: '' },
                { label: "Skin Care", route: '' },
                { label: 'Sun Protection and Tanning', route: '' },
                { label: 'Tattoos and Body Art ', route: '' },
                { label: 'Vision Care ', route: '' },
                { label: 'Weight Management', route: '' },
                { label: "Other Health and Beauty", route: '' },
            ]
        },
        // {
        //     key: '',
        //     label: 'Toys and Hobbies',
        //     src: 'categories/7.png',
        //     sub: [
        //         { label: "Action Figures", route: '' },
        //         { label: 'Beanbag Plush', route: '' },
        //         { label: 'Building Toys ', route: '' },
        //         { label: 'Classic Toys', route: '' },
        //         { label: 'Diecast and Toy  Vehicles', route: '' },
        //         { label: "Educational", route: '' },
        //         { label: "Electronics, Battery and Wind-Up", route: '' },
        //         { label: "Fast Food and Cereal Premiums", route: '' },
        //         { label: 'Model Railroads and Trains', route: '' },
        //         { label: 'Models and Kits', route: '' },
        //         { label: "Outdoor Toys and Structures", route: '' },
        //         { label: "Preschool Toys and Pretend Play", route: '' },
        //         { label: "Puzzles", route: '' },
        //         { label: 'Radio Control and Control Line', route: '' },
        //         { label: 'Robots, Monsters and Space Toys ', route: '' },
        //         { label: 'Stuffed Animals', route: '' },
        //         { label: "Toys Soldiers", route: '' },
        //         { label: 'Trading Card Games', route: '' },
        //         { label: "TV, Movies and Character Toys", route: '' },
        //         { label: "Vintage and Antique Toys", route: '' },
        //     ]
        // },
        {
            key: '',
            label: 'Groceries',
            src: 'categories/18.png',
            sub: [
                { label: "Beverage", route: '' },
                { label: 'Bread/Bakery', route: '' },
                { label: 'Canned/Jarred Goods ', route: '' },
                { label: 'Dairy', route: '' },
                { label: 'Dry/Baking Goods', route: '' },
                { label: "Chocolate, Snack and Sweets", route: '' },
                { label: "Frozen Foods", route: '' },
                { label: "Meat", route: '' },
                { label: 'Produce', route: '' },
                { label: 'Fruit and Vegetable', route: '' },
            ]
        },
        {
            key: '',
            label: 'Specialty Services',
            src: 'categories/19.png',
            sub: [
                { label: "Artistic Services", route: '' },
                { label: 'Custom Clothing and Jewelry', route: '' },
                { label: 'Auction Services ', route: '' },
                { label: 'Graphic and Logo Design', route: '' },
                { label: 'Home Improvement Services', route: '' },
                { label: "Item Based Services", route: '' },
                { label: "Media Editing and Duplication", route: '' },
                { label: "Printing and Personalization", route: '' },
                { label: 'Restoration and Repair', route: '' },
                { label: 'Web and Computer Services', route: '' },
                { label: 'Other Services', route: '' },
            ]
        },
        {
            key: '',
            label: 'Gift Cards and Coupons',
            src: 'categories/20.png',
            sub: [
                { label: "Gift Cards", route: '' },
                { label: 'eBay Gift Cards', route: '' },
                { label: 'Gift Certification ', route: '' },
                { label: 'Coupons', route: '' },
                { label: 'Digital Gifts', route: '' },
            ]
        },
    ]