module.exports = 
{
    "SECTION 1 – ITEMS YOU BARTER": `1. Baristocrat does not manufacture, store, or inspect any of the items sold through our service.<br /><br />2. We provide the venue; the items in Baristocrat are produced, listed, and sold directly by independent barter elites, so Baritocrat cannot and does not make any warranties about their quality and safety.<br /><br />3. Any legal claim related to an item you purchase must be brought directly to the owner of the product. You release Baristocrat from any claims related to items bartered through our service, including defective items, misrepresentations by sellers, or items that caused physical injury (like product liability claims).`,

    "SECTION 2 – CONTENT YOU ACCESS": `1. Baristocrat does not make representations concerning any content posted by users through our services.<br /><br />2. Baristocrat is not responsible for the accuracy, copyright compliance, legality, or decency of content posted by users that you accessed through the services.<br /><br />3. Baristocrat is free from all liability relating to that content.`,

    "SECTION 3 – PEOPLE YOU INTERACT WITH": `1. You can use the Baristocrat to interact with other individuals, either online or in person.<br /><br />2. You understand that we do not screen users of our services, and you release us from all liability relating to your interactions with other users.<br /><br />3. Be careful and exercise caution and good judgment in all interactions with others, especially if you are meeting someone in person.`,

    "SECTION 4 – MEDIUM OF COMMUNICATION": `1. In terms of communicating the products and barter transaction, use the Baristocrat chatbox to discuss, explain and interact with fellow Baristocrat elites.<br /><br />2. Baristocrat does not screen users of our services, and you release us from all liability relating to your interactions with other users from other mediums outside our website.<br /><br />3. Exercise caution and due diligence in interacting to fellow Baristocrat elites.<br /><br />4. Baristocrat is not responsible for examining or evaluating the content of conversations and we do not warrant and will not have any liability or responsibility for any malicious content, or for any other materials, products, or services of fellow users.`,
    
    "SECTION 5 – OPTIONAL TOOLS": `1. Baristocrat may provide you with access to third-party tools over which we neither monitor nor have any control nor Input.<br /><br />2. You acknowledge and agree that we provide access to such tools “as is” and “as available” without any warranties, representations, or conditions of any kind and without any endorsement.<br /><br />3. Baristocrat shall have no liability whatsoever arising from or relating to your use of optional third-party tools.<br /><br />4. Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).<br /><br />5. Baristocrat may also, in the future, offer new services and/or features through the website (including the release of new tools and resources). Such as new features and/or services shall also be subject to these Terms of Service.<br /><br />6. Certain content, products, and services available via our service may include materials from third parties. Third party links on this site may direct you to third party websites that are not affiliated with us.<br /><br />7. Baristocrat is not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third parties.<br /><br />8.  We are not liable for any harm or damages related to the purchase, barter, or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites.<br /><br />9. Baristocrat elites are strongly advised to review carefully the third party’s policies and practices and make sure you understand them before you engage in any transaction.<br /><br />10. Complaints, claims, concerns, or questions regarding third party products should be directed to the third party.`,

    "SECTION 6 – INDEMNIFICATION CLAUSE": `1. Baristocrat users agrees to indemnify and hold harmless the Baristocrat, its respective affiliates, officers, agents, employees, and permitted successors and assigns against any and all claims, losses, damages, liabilities, penalties, punitive damages, expenses, reasonable legal fees, and costs of any kind or amount whatsoever, which result from the barter activity and activities, transactions, products, and services within the Baristocrat.`,

    "Disclaimer for Baristocrat": `If you require any more information or have any questions about our site's disclaimer, please feel free to contact us by email at _________________.<br /><br />Disclaimers for Baristocrat Barter<br /><br />All the information on this website - ____________ - is published in good faith and for general information purpose only. Baristocrat Barter does not make any warranties about the completeness, reliability, and accuracy of this information. Any action you take upon the information you find on this website (Baristocrat Barter), is strictly at your own risk. Baristocrat Barter will not be liable for any losses and/or damages in connection with the use of our website.<br /><br />From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone 'bad'.<br /><br />Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.<br /><br />Consent<br /><br />By using our website, you hereby consent to our disclaimer and agree to its terms.<br /><br />Update<br /><br />Should we update, amend, or make any changes to this document, those changes will be prominently posted here.`
}